FROM golang:1.25-alpine AS builder

WORKDIR /app

# copy the files to the docker
COPY go.mod go.sum ./
RUN go mod download

COPY . .


# copy the source code to the docker
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/server

FROM alpine:3.19

WORKDIR /

COPY --from=builder /app/main .

EXPOSE 5050

CMD ["./main"]